//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import Foundation

class ___VARIABLE_moduleName___Model: ___VARIABLE_moduleName___ModelInterface {
}
