//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class ___VARIABLE_moduleName___Presenter {

    // MARK: - Private properties -

    private unowned let _view: ___VARIABLE_moduleName___ViewInterface
    private let _module: ___VARIABLE_moduleName___ModuleInterface
    private let _model: ___VARIABLE_moduleName___ModelInterface

    // MARK: - Lifecycle -

    init(module: ___VARIABLE_moduleName___ModuleInterface, view: ___VARIABLE_moduleName___ViewInterface, model: ___VARIABLE_moduleName___ModelInterface) {
        _module = module
        _view = view
        _model = model
    }
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface {

}
