//
//  Mod2ViewController.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class Mod2ViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: Mod2PresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension Mod2ViewController: Mod2ViewInterface {
}
