//
//  Mod2Module.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit


//Protocols
protocol Mod2ModuleInterface {
  func navigate(to option: NavigationOptionProtocol, animated:Bool)
  func link(to option:String, animated:Bool)
  func deepNavigate(to option:NavigationPath, animated:Bool)
}

protocol Mod2ModelInterface {
}

protocol Mod2PresenterInterface {
}

protocol Mod2ViewInterface:class {
}

enum Mod2NavigationOption:String, CaseIterable, NavigationOptionProtocol {
  case placeholder
}

class Mod2Module: BaseModule {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Mod2", bundle: nil)

    // MARK: - Module setup -

    init() {
        let identifier = String(describing: Mod2ViewController.self)
        let moduleViewController =  _storyboard.instantiateViewController(withIdentifier: identifier) as! Mod2ViewController

        super.init(viewController: moduleViewController)

        let model = Mod2Model()
        let presenter = Mod2Presenter(module: self, view: moduleViewController, model: model)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension Mod2Module: Mod2ModuleInterface {

  func navigate(to option: NavigationOptionProtocol, animated:Bool = true) {
    let link = option as! Mod2NavigationOption
  }

  func link(to option:String, animated:Bool = true) {
      let routes = Mod2NavigationOption.allCases.map { "\($0)" }
      if(routes.contains(option)) {
        let route = Mod2NavigationOption(rawValue: option)!
        navigate(to: route, animated: animated)
      }
  }

  func deepNavigate(to option:NavigationPath, animated:Bool = true) {
      var path = option
      let route = path.links.removeFirst()
  }
}
