//
//  Mod1ViewModel.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class Mod1ViewModel {

    // MARK: - Private properties -

    private unowned let _view: Mod1ViewInterface
    private let _module: Mod1ModuleInterface
    private let _model: Mod1ModelInterface

    // MARK: - Lifecycle -

    init(module: Mod1ModuleInterface, view: Mod1ViewInterface, model: Mod1ModelInterface) {
        _module = module
        _view = view
        _model = model
        
        
    }
    
    public func navigate(to: NavigationOptionProtocol, animated:Bool = true) {
        _module.navigate(to: to, animated: animated)
    }
    
}

// MARK: - Extensions -

extension Mod1ViewModel: Mod1ViewModelInterface {

}
