//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit


//Protocols

protocol ___VARIABLE_moduleName___ModuleInterface {
    func navigate(to option: ___VARIABLE_moduleName___NavigationOption, animated:Bool)
    func link(to:String, animated:Bool)
}

protocol ___VARIABLE_moduleName___ModelInterface {
}

protocol ___VARIABLE_moduleName___ViewInterface:class {
}

enum ___VARIABLE_moduleName___NavigationOption:String, CaseIterable {
  case placeholder
}

class ___VARIABLE_moduleName___Module: BaseModule {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "___VARIABLE_moduleName___", bundle: nil)

    // MARK: - Module setup -

    init() {
        let identifier = String(describing: ___VARIABLE_moduleName___ViewController.self)
        let moduleViewController =  _storyboard.instantiateViewController(withIdentifier: identifier) as! ___VARIABLE_moduleName___ViewController

        super.init(viewController: moduleViewController)

        let model = ___VARIABLE_moduleName___Model()
        moduleViewController.model = model
    }

}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Module: ___VARIABLE_moduleName___ModuleInterface {

    func navigate(to option: ___VARIABLE_moduleName___NavigationOption, animated:Bool = true) {
    }

    func link(to:String, animated:Bool = true) {
        let routes = ___VARIABLE_moduleName___NavigationOption.allCases.map { "\($0)" }
        if(routes.contains(to)) {
          let route = ___VARIABLE_moduleName___NavigationOption(rawValue: to)!
          navigate(to: route)
        }
    }
}
