//
//  Sub1Model.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import Foundation

class Sub1Model: Sub1ModelInterface {
}
