//
//  Sub1Presenter.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class Sub1Presenter {

    // MARK: - Private properties -

    private unowned let _view: Sub1ViewInterface
    private let _module: Sub1ModuleInterface
    private let _model: Sub1ModelInterface

    // MARK: - Lifecycle -

    init(module: Sub1ModuleInterface, view: Sub1ViewInterface, model: Sub1ModelInterface) {
        _module = module
        _view = view
        _model = model
    }
}

// MARK: - Extensions -

extension Sub1Presenter: Sub1PresenterInterface {

}
