//
//  Sub1ViewController.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class Sub1ViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: Sub1PresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension Sub1ViewController: Sub1ViewInterface {
}
