//
//  RootViewController.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class RootViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: RootPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //presenter.navTo()
    }
    
}

// MARK: - Extensions -

extension RootViewController: RootViewInterface {
}
