//
//  RootPresenter.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class RootPresenter {

    // MARK: - Private properties -

    private unowned let _view: RootViewInterface
    private let _module: RootModuleInterface
    private let _interactor: RootInteractorInterface

    // MARK: - Lifecycle -

    init(module: RootModuleInterface, view: RootViewInterface, interactor: RootInteractorInterface) {
        _module = module
        _view = view
        _interactor = interactor
    }
    
    
}

// MARK: - Extensions -

extension RootPresenter: RootPresenterInterface {
    public func navigate(to option: NavigationOptionProtocol, animated:Bool = true) {
        _module.navigate(to: option, animated: true)
    }
    
    func link(to option: String, animated: Bool) {
        _module.link(to: option, animated: animated)
    }
    
    func deepNavigate(to option: NavigationPath, animated: Bool) {
        _module.deepNavigate(to: option, animated: true)
    }
}
