//
//  RootViewController.swift
//  ModuleExample
//
//  Created by user on 4/21/19.
//  Copyright (c) 2019 Shalom Friss. All rights reserved.
//
//  This file was generated by the Cobra Generator
//

import UIKit

class RootViewController: UIViewController {
    
    // MARK: - Public properties -
    
    @IBOutlet weak var gotoMod1: UIButton!
    var presenter: RootPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        
    }
    @IBAction func gotoMod1Clicked(_ sender: Any) {
        presenter.navigate(to: RootNavigationOption.Mod1, animated: true)
    }
}

// MARK: - Extensions -

extension RootViewController: RootViewInterface {
}
